---
title: "Tutorial 2 – Open Rocket"
author: "DOFPro group"
---

# Modeling with Open Rocket

Open Rocket is a Java app, but a group of dedicated volunteers have created installers for it. Go to [Open Rocket](https://openrocket.info/) to get a version that is appropriate for your computer and OS. There are some outdated hints for usage at [Some Hints for Open Rocket](https://pages.hmc.edu/spjut/AdvRoc/PDF/OpenRocketHints.pdf). Open Rocket (and RasAero) can be used for a number of different tasks. The two principal ones are:

1. Designing a rocket from scratch or planning modifications to an existing kit to achieve some flight objectives.
2. Selecting motors and delays for an existing kit, and verifying that the flight will be stable, safe, and stay within the flight-waiver altitude limit.

## Designing from Scratch or a Kit

The basic procedure is to connect together a series of parts such as a nose cone, a body tube, a motor mount, fins, and a parachute, and then model how this collection of parts will fly when launched with a motor. Open Rocket has a huge database of parts from many different rocket kit manufacturers that have the dimensions, density, mass, and center of mass already entered. In addition, you can either specify all of these properties for any part from scratch, or edit the properties of an existing part in the database.

When beginning from scratch or a kit, your process is to specify all of the components and their relative positions, and then have Open Rocket calculate the total mass, the center of mass, and the center of pressure for your rocket. You then load a model of a specific rocket motor, either from the large database within Open Rocket, downloaded from the web such as from Thrustcurve.org, or that you have created yourself, into your rocket model. Open Rocket will show you the relative positions of the center of mass and the center of pressure. If the center of pressure is not at least one calibre (body-tube diameter) behind the center of mass, you readjust the rocket model until the CP is one calibre behind the CM. Then you run the simulation and examine the results to see if the rocket reached a sufficient velocity before leaving the launch rod or launch rail, if the apogee is to your liking and is lower than the flight-waiver altitude limit where you will be flying, and if the parachute ejects within one second of apogee. If not, modify your ejection-charge delay time, choose a different motor, or modify the rocket parts until you achieve your objectives.

Open Rocket has tools for exporting parts of your design, such as the fins, for use in manufacturing. You can then build your rocket.

## Modeling an Existing Rocket

Once you have constructed your rocket, you will want to measure the actual mass and the actual center of mass. You will find that due to the mass of the adhesive, manufacturing variations, and other causes, your model will not exactly match the mass and center of mass that you calculated when designing the rocket or modeling the kit, although they should be fairly close. Open Rocket has overrides that you can enter for the mass and the center of mass, so you can match your measurements. You can then check if the CM with your chosen motor is at least one calibre in front of the CP. If so, you can run the simulation and examine the results to see if the rocket reached a sufficient velocity before leaving the launch rod or launch rail, if the apogee is to your liking and is lower than the flight-waiver altitude limit where you will be flying, and if the parachute ejects within one second of apogee. If not, you can modify your ejection-charge delay time and/or choose a different motor until you achieve your objectives.

Open Rocket has a database of common rocket kits, and many manufacturers provide RockSim models of their kits on their websites
Open Rocket has a large number of
Create an Open Rocket model of your LOC Weasel from the data you measured. Weigh your avionics assembly or the example model avionics assembly (use 84 g if you don't have access to the avionics, or you don't have access to a scale), and include it as a mass in your model. Record and report the model mass and center of mass as calculated by Open Rocket.

Record and report the actual model mass and center of mass for the example rocket. Comment on the differences from the modeled mass and CM.

## F67-9W Flight

Simulate a flight of your LOC Weasel with an Aerotech F67-9W two different ways:

1. Use Open Rocket and your measured mass and CM.
2. Use the model from Assignment 1 and approximate the F67-9W thrust curve as you think appropriate.

## H128W-14A Flight

Simulate a flight of your LOC Weasel with an Aerotech H128-14A two different ways:

1. Use Open Rocket and your measured mass and CM.
2. Use your 1D model from practice problems 1 and approximate the H128-14A thrust curve as you think appropriate.

For ground conditions, use the likely or reported weather conditions at 9 am in Lucerne Valley on Saturday, 10 February 2024 Compare your results from the two models. Determine if the ejection happens before or after apogee. If it's after apogee, determine the optimal delay adjustment so that the parachute ejects right at apogee. It is not cheating to use the column labeled “Optimum delay” in the Open Rocket results. Rerun your Open Rocket model with the optimal delay. Compare these results with the GPS altitude data from the Weasel H128W-14A flight on 07/08/2023 in [2023-07-08-LogExcel.xlsx](https://pages.hmc.edu/spjut/AdvRoc/FlightData/Weasel/2023-07-08-LogExcel.xlsx).