---
title: "Tutorial 1 – 1-D Rocket Equation with Constant Coefficients"
author: "DOFPro group"
---

In this tutorial, we are going to derive the 1-D integrated equations of motion for a rocket with piecewise-constant thrust, piecewise-constant mass, and constant drag coefficient, $C_D$, starting with the 1-D differential form of the rocket equation. The steps of the derivation as asked in the tutorial are linked. We will use the models to determine drag coefficients and thrust curves from flight data.

# Solutions to the Rocket Equation

The set of differential equations that make up the rocket equation are:

$$
\label{rocket}
\vec{a}=\dot{\vec{v}}=\frac{\vec{T}}{m}+\vec{g}-\frac{1}{2}C_D A_P \frac{\rho}{m}\vec{v}|\vec{v}|
$$ {#eq-1}


and

$$
\label{mass}
\dot{m}=\frac{|\vec{T}|}{|\vec{v_e}|}
$$ {#eq-2}

Depending on what assumptions you make, you can get different solutions to the rocket equation.
This tutorial proves or derives several of them. To explain the difference: _prove_ means
that you are given a solution to the differential equation, and you prove by plugging-in
to the DE that it solves the equation and the boundary or initial conditions, _derive_
means to use the solution techniques for differential equations and determine a solution
that solves the DE and the boundary or initial conditions.

## 1-D Constant Thrust, Constant Mass, Constant $g$, Drag Coefficient $C_D$
Assume that the change in rocket mass is small compared to the rocket mass. The rocket
ascends in the positive vertical, $x$, direction, and begins at time, $t_0$, with position,
$x_0$, velocity, $v_0$, and constant thrust, $T$. Further define $v_{\text{max}}$ as

$$
\label{vmax}
v_{\text{max}} = \sqrt{\frac{2(T-mg)}{\rho C_D A_P}}
$$ {#eq-3}

and $b$ as

$$
\label{b}
b=\frac{T-mg}{m}
$$ {#eq-4}

@eq-1 then becomes

$$
\label{rocket1D}
a=\dot{v}=b-\frac{1}{2}C_D A_P \frac{\rho}{m}v|v|
$$  {#eq-5}

Prove that the solution for $v_0 < v_{\text{max}}$ is

$$
v=v_{\text{max}}\tanh{\left[\frac{b}{v_{\text{max}}}(t-t_0)+\tanh^{-1}{\frac{v_0}{v_{\text{max}}}}\right]}
$$  {#eq-6}

and
$$
x-x_0= \frac{v^2_{\text{max}}}{b}\left\{\ln{\left[\cosh{\left(\frac{b}{v_{\text{max}}}(t-t_0)+\tanh^{-1}{\frac{v_0}{v_{\text{max}}}}\right)}\right]-\ln{\left[\cosh{\left(\tanh^{-1}{\frac{v_0}{v_{\text{max}}}}\right)}\right]}}\right\}
$$  {#eq-7}

You can eliminate the absolute value sign by considering whether correct factor is $-v^2$ or $v^2$ depending
on which direction is positive $x$ and whether the drag opposes the motion or adds to the motion.

Prove that the solution for $v_0 > v_{\text{max}}$ is

$$
v=v_{\text{max}}\coth{\left[\frac{b}{v_{\text{max}}}(t-t_0)+\coth^{-1}{\frac{v_0}{v_{\text{max}}}}\right]}
$$  {#eq-8}

and

$$
x-x_0= \frac{v^2_{\text{max}}}{b}\left\{\ln{\left[\sinh{\left(\frac{b}{v_{\text{max}}}(t-t_0)+\coth^{-1}{\frac{v_0}{v_{\text{max}}}}\right)}\right]-\ln{\left[\sinh{\left(\coth^{-1}{\frac{v_0}{v_{\text{max}}}}\right)}\right]}}\right\}
$$  {#eq-9}

::: {.callout-tip collapse="true"}
## Solution

Solution to above derivation.
:::

## 1-D Coasting Ascent (No Thrust), Constant $g$, Drag Coefficient $C_D$
The positive vertical direction is $x$. The rocket
ascends in the positive vertical direction, and begins at time, $t_0$, with position,
$x_0$, and velocity, $v_0$. Further define $v_t$ as

$$
v_t = \sqrt{\frac{2mg}{\rho C_D A_P}}.
$$  {#eq-10}

@eq-1 then becomes

$$
a=\dot{v}=-g\left({1+\frac{v^2}{v_t^2}}\right)
$$  {#eq-11}

Prove that the solution is

$$
\label{CoastV}
v=v_t\tan{\left[\frac{-g}{v_t}(t-t_0)+\tan^{-1}{\frac{v_0}{v_t}}\right]}
$$  {#eq-12}

and

$$
\label{CoastX}
x-x_0= \frac{v^2_t}{g}\left(\ln{\left\{\cos{\left[\frac{g}{v_t}(t-t_0)-\tan^{-1}{\frac{v_0}{v_t}}\right]}\right\}}+\ln{\sqrt{1+\frac{v_0^2}{v_t^2}}}\right)
$$  {#eq-13}

## 1-D Coasting Descent from Apogee (No Thrust), Constant $g$, Drag Coefficient $C_D$
The positive vertical direction is $x$. The rocket
descends in the negative vertical direction, and begins at time, $t_{\text{apogee}}$, with position,
$x_{\text{apogee}}$, and velocity, $v_{\text{apogee}}=0$. Further define $v_t$ as

$$
v_t = \sqrt{\frac{2mg}{\rho C_D A_P}}.
$$  {#eq-14}

Simplify @eq-5 for these conditions and prove that the solution is

$$
v=v_t\tanh{\left[\frac{-g}{v_t}(t-t_{\text{apogee}})\right]}
$$  {#eq-15}

and

$$
\label{DescPos}
x-x_{\text{apogee}}= \frac{v^2_t}{-g}\ln{\left\{\cosh{\left[\frac{-g}{v_t}(t-t_{\text{apogee}})\right]}\right\}}
$$  {#eq-16}

# Applying the Solutions
Use the above formulas to determine useful flight information

## Time from Apogee to Ground
Use @eq-16 to determine the time, $t_{\text{desc}}$ for a rocket to descend from apogee to the
ground. For a ballistic fall you would use the $C_D$ of the rocket, and for a parachute
descent, you would use the area and $C_D$ of the parachute.

Show that for $gx_0/v_t^2>100$ the approximation

$$
t-t_{\text{apogee}}=\frac{x_{\text{apogee}}}{v_t}+\frac{v_t}{g}\ln{2}
$$  {#eq-17}

is accurate and doesn't have the computational difficulties of your above solution.

## Time from Burnout to Apogee
Use @eq-12 and the fact that $v=0$ at apogee to determine the time from burnout
to apogee.

## Distance from Burnout to Apogee
Use the result from the previous step and @eq-13 to determine the distance from
burnout to apogee.

## Flight Milestones
For the flight of a LOC Weasel on an F67-9W motor, calculate:

  - the velocity and altitude at burnout,
  - the time from liftoff to apogee (ignore the 9-second delay for this part),
  - the difference between the time to apogee and the 9-second delay,
  - the altitude at apogee,
  - the time required for a ballistic fall from apogee,
  - the velocity at impact for a ballistic fall
  - the time required for a parachute descent from apogee,
  - the velocity at landing for a parachute descent from apogee.
  
Data for a LOC Weasel with avionics on an F67-9W: <!-- Fix ASAP to With Avionics -->

Item            | Value
----------------|------
mass (no motor) | 453.0 g
mass (w motor)  | 534.0 g
Propellant mass | 30 g
CG (no motor)   | 23.72 in
CG (w motor)    | 27.48 in
diameter        | 1.64 in
$C_D$           | 0.70
motor data      | [see thrustcurve.org](https://www.thrustcurve.org/motors/AeroTech/F67W/)
  
## Comparison with Open Rocket/Rocksim
How do your calculations compare with the results from Open Rocket or Rocksim? An Open Rocket
model for the above rocket is [here](../SimModels/LOC-Weasel-E178.ork).
Open Rocket is a Java app, but a group of dedicated volunteers have created installers for
it. Go to [Open Rocket](https://openrocket.info/) to get a version that is appropriate for
your computer and OS. There are some outdated hints for usage at
[Some Hints for Open Rocket](../PDF/OpenRocketHints.pdf).


# Discussion

The purpose of this tutorial was threefold:

1. To give you an appreciation for the kind of analytical solutions that can be developed from the rocket equation.
2. To give you a set of tools for exploring questions about ranges of solutions for the rocket equation, e.g., how do the peak velocity and apogee vary as you keep the motor impulse constant but vary the burn time.
3. To show you that for a real rocket with real motors, it's much easier to use a simulator (a model that someone else has developed) such as Open Rocket than to derive and use your own solution to the rocket equation.

Now that you have these tools, it doesn't hurt to check your Open Rocket simulations against them to see if both make sense.