project:
  type: website

website:
  title: "High Power Rocketry"
  navbar:
    logo: DOFPro_D7_Red_Flame_No_Background_cropped.png
    logo-alt: "DOFPro Logo"
    logo-href: https://dofpro.org
    left:
      - text: Intro
        menu:
        - href: intro/index.qmd
          text: Intro
        - href: intro/cert.qmd
          text: Certification
      - href: safety/
        text: Safety
      - text: Construction
        menu:   
        - href: const/index.qmd
          text: General Tips
        - href: const/vulcanite.qmd
          text: "Vulcanite Dual Deploy"    
        - href: const/DX3.qmd
          text: 1.6" miniDX3
        - href: const/55mmClassRocket.qmd
          text: 55mm HMC Rocket
        - href: const/33mmClassRocket.qmd
          text: 33mm HMC Rocket
        - href: const/standardVulcanite.qmd
          text: Standard Vulcanite
            
      - text: Modeling
        menu:
          - href: model/index.qmd
            text: Overview
          - href: model/softWareDownloads.qmd
            text: "Software Downloads"
      - text: "Data Analysis"
        menu:
        - href: instr/index.qmd
          text: "Data Analysis"
        - href: instr/baroalt.qmd
          text: Altimeters

      - text: Flight Data
        menu:
        - href: fltdata/index.qmd
          text: Overview
        - href: fltdata/FlightData.qmd
          text: Launch Data

      - href: archive/
        text: Archive
      
      - text: DOFPro
        menu:
        - href: https://dofpro.org
          text: "DOFPro Home"
        - href: https://dofpro.org/CTP/
          text: "Chem. Therm. Proc."

format:
  html:
    theme: materia
    css: styles.css
    toc: true

execute:
  freeze: auto