project:
  type: website

website:
  title: "High Power Rocketry"
  navbar:
    left:
      - text: Intro
        menu:
        - href: intro/index.qmd
          text: Intro
        - href: intro/cert.qmd
          text: Certification
      - href: safety/
        text: Safety
      - href: const/
        text: Construction
      - href: model/
        text: Modeling
      - href: instr/
      - text: "Data Analysis"
        menu:
        - href: instr/index.qmd
          text: "Data Analysis"
        - href: instr/baroalt.qmd
          text: Altimeters
      - href: fltdata/
        text: "Flight Data"
      - href: archive/
        text: Archive
      
      - text: DOFPro
        menu:
        - href: https://dofpro.org
          text: "DOFPro Home"
        - href: https://dofpro.org/CTP/
          text: "Chem. Therm. Proc."

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

execute:
  freeze: auto



