---
title: "Flight Data Archive"
author: "DOFPro group"
---


There are a number of file formats used for the flight data. There are the native formats generated by the avionics and software, and exports into .txt, .cvs, and Excel formats. We recommend the following file formats:



| Extention | Hardware | Software | Platform |
|-----------|------|------|------|
| .pf2   | PerfectFlite Pnut or Stratologger   | [PerfectFlite Data Cap][PDC] | Windows, Mac |
| .FIPa  | Featherweight Raven    | [Featherweight Interface Program][FIP]    | Windows |
| .csv   | Featherweight Raven    | Microsoft Excel or other spreadsheet    | Windows, Mac |
| .xtra  | AIM XTRA    | [AIM XTRA][AX]    | Windows |
| .csv   | AIM XTRA or AIM Base   | Microsoft Excel or other spreadsheet    | Windows, Mac |
| .kml   | AIM XTRA or AIM Base   | Google Earth    | Windows, Mac |
| .TXT   | New Teensy Data Logger    | [ScanTeensyDataLogger.m][STD]    | Windows, Mac |
| .TXT   | Teensy Data Logger   | [ParseTeensyLogger.m][PTL]    | Windows, Mac |
| .TXT   | Eggfinder or EF Mini    | [ParseTeensyLogger.m][PTL]    | Windows, Mac |

: File Formats {#tbl-letters}

# LabVIEW

To plot data from Raven .csv files in LabVIEW, use the [ReadDisplayRavenCSV.vi1](https://pages.hmc.edu/spjut/AdvRoc/LabVIEWModels/ReadDisplayRavenCSV.vi).

To plot data from .pf2 files in LabVIEW, use the [ReadDisplayPF2.vi](https://pages.hmc.edu/spjut/AdvRoc/LabVIEWModels/ReadDisplayPF2.vi).

To plot data from either AIM XTRA or AIM BASE .csv files in LabVIEW, use the [ReadDisplayAIM.vi](https://pages.hmc.edu/spjut/AdvRoc/LabVIEWModels/ReadDisplayAIM.vi).

# MATLAB

To plot data from Raven .csv files in MATLAB, use the [ReadPlotFIPcsv.m](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/ReadPlotFIPcsv.m).

To plot data from .pf2 files in MATLAB, write your own .m file.

To plot data from either AIM XTRA or AIM BASE .csv files in MATLAB, use the [ReadPlotAIMData.m](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/ReadPlotAIMData.m).

To read and process flight data from the Teensy Logger and the Eggfinder or Eggfinder Mini, use the [ParseTeensyLogger.m](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/ParseTeensyLogger.m). You'll also need [myDateNum.m](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/myDateNum.m),[myStrLat.m](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/myStrLat.m), and [myStrLon.m](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/myStrLon.m).

To read and process flight data from the New Teensy Data Logger (either the small or the large) use the [ScanTeensyDataLogger.m](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/ScanTeensyDataLogger.m).

To combine data from the New Teensy Data Loggers with GPS data and Open Rocket data use [ScanTeensyDataLoggerGPSRotTempAdventurer](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/ScanTeensyDataLoggerGPSRotTempAdventurer.m).

To read and process flight data from the newest Teensy Data Loggers that have a non-functioning IMU, use the [ScanFaultyTeensyDataLogger.m](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/ScanFaultyTeensyDataLogger.m).

# Motor Data Files

Below are datasets on functionality of a variety of motors and their manufacturers. You can also find data by going to [ThrustCurve.org](http://www.thrustcurve.org/searchpage.jsp) and entering the manufacturer and common name.

[Sortable database of Aerotech motors](https://pages.hmc.edu/spjut/AdvRoc/ExcelModels/AerotechMotors.xlsx)
[Sortable database of CTI motors](https://pages.hmc.edu/spjut/AdvRoc/ExcelModels/CesaroniMotors.xlsx)

| Manufacturer | Motor | Data | 
|-----------|------|------|
| Estes | C6-5 | [data](https://www.thrustcurve.org/motors/Estes/C6/) |
| Estes | C6-7 | [data](https://www.thrustcurve.org/motors/Estes/C6/) |
| Quest | C6-5 | [data](https://www.thrustcurve.org/motors/Quest/C6/) |
| Aerotech | D13-10W | [data](https://www.thrustcurve.org/motors/AeroTech/D13W/) | 
| Estes | E9-6 | [data](https://www.thrustcurve.org/motors/Estes/E9/) |
| Estes | E12-6 | [data](https://www.thrustcurve.org/motors/Estes/E12/) |
| Aerotech | F67-9W | [data](https://www.thrustcurve.org/motors/AeroTech/F67W/) |
| Aerotech | G80T-14 | [data](https://www.thrustcurve.org/motors/AeroTech/G80T/) | 
| Aerotech | G69N-P | [data](https://www.thrustcurve.org/motors/AeroTech/G69N/) |
| Aerotech | H128W | [data](https://www.thrustcurve.org/motors/AeroTech/H128W/) |
| Aerotech | H148R | [data](https://www.thrustcurve.org/motors/AeroTech/H148R/) |
| Aerotech | J270W | [data](https://www.thrustcurve.org/motors/AeroTech/H128W/) | 
| Aerotech | J500G | [data](https://www.thrustcurve.org/motors/AeroTech/J500G/) |
| Aerotech | J510W | [data](https://www.thrustcurve.org/motors/AeroTech/J510W/) |
| Aerotech | J570W | [data](https://www.thrustcurve.org/motors/AeroTech/J570W/) |
| Aerotech | J825R | [data](https://www.thrustcurve.org/motors/AeroTech/J825R/) | 
| CTI | J150 | [data](https://www.thrustcurve.org/motors/Cesaroni/949J150-P/) |
| CTI | J354 | [data](https://www.thrustcurve.org/motors/Cesaroni/819J354-16A/) |
| CTI | J394 | [data](https://www.thrustcurve.org/motors/Cesaroni/970J394-13A/) |
| CTI | J530 | [data](https://www.thrustcurve.org/motors/Cesaroni/1115J530-15A/) | 
 

# Weather Patterns

When considering to launch for the first time (or anytime for that matter) it is important to be conscientious of weather patterns at the lauch site to minimize the possibility of errors. As a result, the Harvey Mudd College Rocketry course has compiled set of data about Lucerne Valley weather for other rocketeers to take advantage of.

A temperature Rocket was used to measure the temperature at Lucerne Valley. The available data are shown below:

| Date | Plot | Data | 
|-----------|------|------|
| 7 JUN 2013 | [7jun2013](https://pages.hmc.edu/spjut/NewE80/FlightData/LucValTempAltPlot7JUN2013.pdf) | [data7613](https://pages.hmc.edu/spjut/NewE80/FlightData/Data201201/QSB4-4S1T2F1_20120124.pfa) |
| 11 AUG 2013 | [11Aug2013](https://pages.hmc.edu/spjut/NewE80/FlightData/LucValTempAltPlot11AUG2013.pdf) | [data1182023](https://pages.hmc.edu/spjut/NewE80/FlightData/LucValTempAltData11AUG2013.xlsx) |
| 19 APR 2014 | [1992014](https://pages.hmc.edu/spjut/NewE80/FlightData/LucValTempAltPlot19APR2014.pdf) | [data1982014](https://pages.hmc.edu/spjut/NewE80/FlightData/LucValTempAltPlot19APR2014.pdf) |


Table of Lucerne Valley Temperature Data

: Motor Data {#tbl-letters}

[PDC]: http://www.perfectflite.com/Download.html
[FIP]: https://www.featherweightaltimeters.com/interface-program.html
[AX]: http://entacore.com/electronics/aimxtra
[STD]: ScanTeensyDataLogger.m
[PTL]: https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/ParseTeensyLogger.m