---
title: "Practice Problems 3"
author: "DOFPro group"
---

An analysis of the flight data recorded by the on-board avionics can reveal quite a bit of the performance of a rocket. The analysis usually involves starting with the rocket equation, and manipulating it to permit data fitting to determine performance data. This assignment will give you a chance to analyze flight data to look at the coefficient of drag ($ğ¶_ğ·$), the thrust curve of the motor, and the rotation of the rocket about the axial direction, essentially the roll, during the boost phase.

If you prefer, you can analyze the data from your own flight, rather than the ones listed in the problem.

## Average $ğ¶_ğ·$

The post-boost portion of the rocket flight can be used to look at $ğ¶_ğ·$, as explained in $ğ¶_ğ·$. From [Post-Boost Flight Data](https://pages.hmc.edu/spjut/AdvRoc/PDF/CDfromPostBoost.pdf), the average $ğ¶_ğ·$ can be determined by a plot of $\frac{âˆ’2ğ‘š}{ğ´_ğ‘ğœŒ}(ğ‘+ğ‘”)$ versus $ğ‘£^2$ or a plot of $\frac{âˆ’2ğ‘š}{ğ´_ğ‘ğœŒ}ğ‘ versus $ğ‘£_2$. Use the data from the first seven flights of the [Madcow Mini DX3](https://dofpro.org/RCK/fltdata/FlightData.html) to determine  average $ğ¶_ğ·$ for this rocket. Include a 95% confidence intervals on the value of $ğ¶_ğ·$. There are refreshers on statistics [here](https://drive.google.com/file/d/1_T4TviLt9oUw6PXEDxpSGv6yuUdPVigi/view?usp=sharing) and [here](https://www.youtube.com/playlist?list=PLDA3QBjykWVxDiGsN1Xpm2ynGekSvEC9E). The MATLAB file to parse the data is [ParseTeensyLoggerEggfinder.m](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/ParseTeensyLoggerEggfinder.m). Note that it doesn't contain the code to get the average ğ¶ğ· or the thrust curve. You are on your own to add that code.

## $ğ¶_ğ·$ as a Function of Velocity

If your accelerometers are good enough, you can actually calculate the $ğ¶_ğ·$ as a function of velocity. As explained in $ğ¶_ğ·$ From [Post-Boost Flight Data](https://dofpro.org/RCK/fltdata/FlightData.html),

$$
ğ¶_ğ·=âˆ’\frac{2ğ‘š(ğ‘+ğ‘”)}{ğ´_ğ‘ğœŒğ‘£^2}
$$
(1)

and you can then plot $ğ¶_ğ·$ versus ğ‘£. However, the most accurate $ğ¶_ğ·$ plot is as a function of Mach number, and not just velocity. The equation relating the speed of sound, ğ‘, to the absolute temperature, ğ‘‡, for an ideal gas is

$$
ğ‘=\sqrt{\frac{ğ›¾ğ‘…ğ‘‡}{ğ‘€}}
$$
(2)

where ğ›¾ is the ratio of heat capacities (ğ›¾=1.4 for air), ğ‘… is the molar gas constant, and ğ‘€ is the molar mass or molecular weight of the air.

Generate plots of the $ğ¶_ğ·$ as a function of velocity for either the 17 Apr 2021 flights of the Class Adventurer Prototype on the Aerotech J510W and the CTI J530 or the 11 Feb 2023 flights of the Weasel on the Aerotech G80 and the Dual Deploy Vulcanite on the Aerotech I140. There is also a [MATLAB](https://pages.hmc.edu/spjut/AdvRoc/MATLABModels/ScanTeensyDataLogger.m) file that will make the process easier. If possible, include error bounds on your plot. Compare your results with the $ğ¶_ğ·$ versus velocity data for the same rocket and motors from any of Rocksim, Open Rocket, or RASAero II. There is a MATLAB file that will make the process easier.

Generate plots of the $ğ¶_ğ·$ as a function of Mach number for the 9 Sep 2017 flights of the E190 Prototype rocket on the CTI J354 and the Aerotech J825R. Correct the Mach number for the temperature as a function of altitude and correct the air density for temperature and pressure as a function of altitude, and molecular weight as a function of relative humidity. Include error bounds on your plot. Compare your results with the $ğ¶_ğ·$ versus velocity data for the same rocket from any of Rocksim, Open Rocket, or RASAero II.

## Thrust Curve

With either your average $ğ¶_ğ·$ or your $ğ¶_ğ·$ as a function of velocity, you are able to calculate the thrust curve for your motor from the accelerometer data. As explained in [Thrust Curve from Acceleration and Velocity Flight Data](https://pages.hmc.edu/spjut/AdvRoc/PDF/ThrustCurveFromFlightData.pdf) you can calculate the thrust from an iterative solution of

$$
ğ‘‡=ğ‘š(ğ‘+ğ‘”)+\frac{1}{2}ğ¶_ğ·ğ´_ğ‘ğœŒğ‘£^2
$$
(3)

and

$$
ğ‘š(ğ‘¡)=ğ‘š_0+\frac{1}{ğ‘£_ğ‘’}âˆ«^ğ‘¡_{ğ‘¡_0}ğ‘‡ğ‘‘ğ‘¡
$$
(4)

Using the data from either the 17 Apr 2021 flights of the Class Adventurer Prototype on the Aerotech J510W and the CTI J530 or the 11 Feb 2023 flights of the Weasel on the Aerotech G80 and the Dual Deploy Vulcanite on the Aerotech I140, plot the thrust curves and compare with the thrust curves from ThrustCurve.org. There is a MATLAB file that will make the process easier.

From the data for first six flights of the Estes Top Shot calculate the thrust curves for the Estes E12 motor. Give the mean and 95% confidence intervals for the burn time, peak thrust, average thrust, and total impulse. Compare with the data on ThrustCurve.org for the Estes E12. There is a VI, RavenCSVCDThrustCalcs.vi, that will make the process easier.

