---
title: "Practice Problems 1"
author: "DOFPro group"
---

In this first set of practice problems, we are going to be starting with the 1-D rocket equation. We will prove that the given models solve the equation for the chosen restrictions. We will use the models to determine drag coefficients and thrust curves from flight data.

The set of equations that make up the rocket equation are:
$$
\vec{ğ‘} = \dot{\vec{ğ‘£}} = \frac{\vec{T}}{m}+ \vec{ğ‘”} âˆ’\frac{1}{2}{ğ¶_ğ·}{ğ´_ğ‘ƒ}{\frac{ğœŒ}{m}}\vec{ğ‘£}|\vec{ğ‘£}|
$$
(1)

and

$$
\dot{ğ‘š}=\frac{|\vec{ğ‘‡}|}{|\vec{ğ‘£_ğ‘’}|}
$$
(2)

## 1-D Constant Thrust, Constant Mass, Constant ğ‘”, Drag Coefficient $ğ¶_ğ·$

Depending on what assumptions you make, you can get different solutions to the rocket equation. This practice problem proves or derives several of them. To explain the difference: prove means that you are given a solution to the differential equation, and you prove by plugging-in to the DE that it solves the equation and the boundary or initial conditions, derive means to use the solution techniques for differential equations and determine a solution that solves the DE and the boundary or initial conditions.

Assume that the change in rocket mass is small compared to the rocket mass. The rocket ascends in the positive vertical, ğ‘¥, direction and begins at time, $ğ‘¡_0$ , with position, $ğ‘¥_0$ , velocity, $ğ‘£_0$, and constant thrust, ğ‘‡. Further define $ğ‘£_{max}$ as

$$
ğ‘£_{max}=\sqrt{\frac{2(ğ‘‡âˆ’ğ‘šğ‘”)}{ğœŒğ¶_ğ·ğ´_ğ‘ƒ}}
$$
(3)

and ğ‘ as

$$
ğ‘=\frac{ğ‘‡âˆ’ğ‘šğ‘”}{ğ‘š}
$$
(4)

Equation 1 then becomes

$$
ğ‘=\dot{ğ‘£}=ğ‘âˆ’\frac{1}{2}ğ¶_ğ·ğ´_ğ‘ƒ\frac{ğœŒ}{ğ‘š}ğ‘£|ğ‘£|
$$
(5)

Prove that the solution for $ğ‘£_0<ğ‘£_{max}$ is

$$
ğ‘£=ğ‘£_{max}tanh[\frac{ğ‘}{ğ‘£_{max}}(ğ‘¡âˆ’ğ‘¡_0)+{tanh}^{âˆ’1}\frac{ğ‘£_0}{ğ‘£_{max}}]
$$
(6)

and

$$
ğ‘¥âˆ’ğ‘¥_0=\frac{{ğ‘£_{max}}^2}{ğ‘}[ln[cosh(\frac{ğ‘}{ğ‘£_{max}}(ğ‘¡âˆ’ğ‘¡_0)+{tanh}^{âˆ’1}\frac{ğ‘£_0}{ğ‘£_{max}})]âˆ’ln[cosh({tanh}^{âˆ’1}\frac{ğ‘£_0}{ğ‘£_{max}})]]
$$
(7)

You can eliminate the absolute value sign by considering whether correct factor is $âˆ’ğ‘£^2$$ or $ğ‘£^2$ depending on which direction is positive ğ‘¥ and whether the drag opposes the motion or adds to the motion.

Prove that the solution for $ğ‘£_0>ğ‘£_{max}$ is

$$
ğ‘£=ğ‘£_{max}coth[\frac{ğ‘}{ğ‘£_{max}}(ğ‘¡âˆ’ğ‘¡0)+{coth}^{âˆ’1}\frac{ğ‘£_0}{ğ‘£_{max}}]
$$
(8)

and

$$
ğ‘¥âˆ’ğ‘¥_0=\frac{{ğ‘£_{max}}^{2}}{ğ‘}[ln[sinh(\frac{ğ‘}{ğ‘£_{max}}(ğ‘¡âˆ’ğ‘¡0)+{coth}^{âˆ’1}\frac{ğ‘£_0}{ğ‘£_{max}})]âˆ’ln[sinh({coth}^{âˆ’1}\frac{ğ‘£_0}{ğ‘£_{max}})]]
$$
(9)

## 1-D Coasting Ascent (No Thrust), Constant ğ‘”, Drag Coefficient $ğ¶_ğ·$

The positive vertical direction is ğ‘¥. The rocket ascends in the positive vertical direction, and begins at time, $ğ‘¡_0$, with position, $ğ‘¥_0$, and velocity, $ğ‘£_0$. Further define $ğ‘£_ğ‘¡$ as

$$
ğ‘£_ğ‘¡=\sqrt{\frac{2ğ‘šğ‘”}{ğœŒğ¶_ğ·ğ´_ğ‘ƒ}}
$$
(10)

Equation 1 then becomes

$$
ğ‘=\dot{ğ‘£}=âˆ’ğ‘”(1+\frac{ğ‘£^2}{ğ‘£_t^2})
$$
(11)

Prove that the solution is

$$
ğ‘£=ğ‘£_ğ‘¡tan[\frac{âˆ’ğ‘”}{ğ‘£_ğ‘¡}(ğ‘¡âˆ’ğ‘¡_0)+{tan}^{âˆ’1}\frac{ğ‘£_0}{ğ‘£_ğ‘¡}]
$$
(12)

and

$$
ğ‘¥âˆ’ğ‘¥_0=\frac{ğ‘£^2_ğ‘¡}{ğ‘”}(ln(cos[\frac{ğ‘”}{ğ‘£_ğ‘¡}(ğ‘¡âˆ’ğ‘¡0)âˆ’{tan}^{âˆ’1}\frac{ğ‘£_0}{ğ‘£_ğ‘¡}])+ln\sqrt{1+\frac{ğ‘£^2_0}{ğ‘£^2_ğ‘¡}})
$$
(13)

## 1-D Coasting Descent from Apogee (No Thrust), Constant ğ‘”, Drag Coefficient $ğ¶_ğ·$

The positive vertical direction is ğ‘¥. The rocket descends in the negative vertical direction, and begins at time, $ğ‘¡_{apogee}$, with position, $ğ‘¥_{apogee}$, and velocity, $ğ‘£_{apogee}=0$. Further define $ğ‘£_ğ‘¡$ as

$$
ğ‘£_ğ‘¡=\sqrt{\frac{2ğ‘šğ‘”}{ğœŒğ¶_ğ·ğ´_ğ‘ƒ}}
$$
(14)

Simplify Equation 5 for these conditions and prove that the solution is

$$
ğ‘£=ğ‘£_ğ‘¡tanh[\frac{âˆ’ğ‘”}{ğ‘£_ğ‘¡}(ğ‘¡âˆ’ğ‘¡_{apogee})]
$$
(15)

and

$$
ğ‘¥âˆ’ğ‘¥_{apogee}=\frac{ğ‘£^2_ğ‘¡}{âˆ’ğ‘”}ln(cosh[\frac{âˆ’ğ‘”}{ğ‘£_ğ‘¡}(ğ‘¡âˆ’ğ‘¡_{apogee})])
$$
(16)

## Time from Apogee to Ground

Use Equation 16 to determine the time, $ğ‘¡_{desc}$ for a rocket to descend from apogee to the ground. For a ballistic fall you would use the $ğ¶_ğ·$ of the rocket, and for a parachute descent, you would use the area and $ğ¶_ğ·$ of the parachute.

Show that for $ğ‘”ğ‘¥_0/ğ‘£^2_ğ‘¡>100$ the approximation

$$
ğ‘¡âˆ’ğ‘¡_{apogee}=\frac{ğ‘¥_{apogee}}{ğ‘£_ğ‘¡}+\frac{ğ‘£_ğ‘¡}{ğ‘”}ln2
$$
(17)

is accurate and doesn't have the computational difficulties of your above solution.

* Use Equation 12 and the fact that ğ‘£=0 at apogee to determine the time from burnout to apogee.

* Use the result from the previous step and Equation 13 to determine the distance from burnout to apogee.

For the flight of a LOC Weasel on an F67-9W motor, calculate:

* the velocity and altitude at burnout,
* the time from liftoff to apogee (ignore the 9-second delay for this part),
* the difference between the time to apogee and the 9-second delay,
* the altitude at apogee,
* the time required for a ballistic fall from apogee,
* the velocity at impact for a ballistic fall
* the time required for a parachute descent from apogee,
* the velocity at landing for a parachute descent from apogee.

Data for a LOC Weasel with avionics on an F67-9W:

| Item | Value |
|-----------|------|
| Mass (no motor) | 453.0 g |
| Mass (w motor) | 534.0 g |
| Propellant mass | 30 g |
| CG (no motor) | 23.72 in |
| CG (w motor) | 27.48 in |
| diameter | 1.64 in |
| $C_D$ | 0.70 |
| motor data | [See Thrustcurve.org](https://www.thrustcurve.org/motors/AeroTech/F67W/) |

## Comparison with Open Rocket/Rocksim

How do your calculations compare with the results from Open Rocket or Rocksim? An Open Rocket model for the above rocket is [here](https://pages.hmc.edu/spjut/AdvRoc/SimModels/LOC-Weasel-E178.ork). Open Rocket is a Java app, but a group of dedicated volunteers have created installers for it. Go to [Open Rocket](https://openrocket.info/) to get a version that is appropriate for your computer and OS. There are some outdated hints for usage at Some [Hints for Open Rocket](https://pages.hmc.edu/spjut/AdvRoc/PDF/OpenRocketHints.pdf).