---
title: "Practice Problems 2"
author: "DOFPro group"
---

## Open Rocket

Open Rocket is a Java app, but a group of dedicated volunteers have created installers for it. Go to [Open Rocket](https://openrocket.info/) to get a version that is appropriate for your computer and OS. There are some outdated hints for usage at [Some Hints for Open Rocket](https://pages.hmc.edu/spjut/AdvRoc/PDF/OpenRocketHints.pdf).

Create an Open Rocket model of your LOC Weasel from the data you measured. Weigh your avionics assembly or the example model avionics assembly (use 84 g if you don't have access to the avionics, or you don't have access to a scale), and include it as a mass in your model. Record and report the model mass and center of mass as calculated by Open Rocket.

Record and report the actual model mass and center of mass for the example rocket. Comment on the differences from the modeled mass and CM.

## F67-9W Flight

Simulate a flight of your LOC Weasel with an Aerotech F67-9W two different ways:

1. Use Open Rocket and your measured mass and CM.
2. Use the model from Assignment 1 and approximate the F67-9W thrust curve as you think appropriate.

## H128W-14A Flight

Simulate a flight of your LOC Weasel with an Aerotech H128-14A two different ways:

1. Use Open Rocket and your measured mass and CM.
2. Use your 1D model from practice problems 1 and approximate the H128-14A thrust curve as you think appropriate.

For ground conditions, use the likely or reported weather conditions at 9 am in Lucerne Valley on Saturday, 10 February 2024 Compare your results from the two models. Determine if the ejection happens before or after apogee. If it's after apogee, determine the optimal delay adjustment so that the parachute ejects right at apogee. It is not cheating to use the column labeled “Optimum delay” in the Open Rocket results. Rerun your Open Rocket model with the optimal delay. Compare these results with the GPS altitude data from the Weasel H128W-14A flight on 07/08/2023 in [2023-07-08-LogExcel.xlsx](https://pages.hmc.edu/spjut/AdvRoc/FlightData/Weasel/2023-07-08-LogExcel.xlsx).