---
title: "Mini DX3 Assembly Instructions"
author: "DOFPro group"
---

The image below displays almost all of the parts that come in the kit.
**image**

The following is a list of parts that are required separately from the kit.

* An Estes 29mm motor retainer
* Three #2-56 × 3/16" pan-head screws

## Step 1: Sanding

Sand every surface to be epoxied (including interior surfaces) with 80-to-110 grit sandpaper. You may have to think about the assembly sequence to figure out where to sand. Don't forget about the inside of the Estes motor retainer. Pretty much the entire exterior of the motor mount should be sanded or roughed up

## Step 2: Motor Mount Assembly

Test fit centering rings over the motor mount tube and sand centering rings if necessary.

Also test fit the centering rings in the body tube and sand the rings if necessary.

Place the inside part of your Estes motor retainer on one end of the motor mount tube. Make sure it is fully seated. Using a pen or pencil, mark the tube where the motor retainer hits the tube.

Screw on the outside of the motor retainer.

Insert the assembly into the slotted end of the rocket body tube so that the motor tube is still seated in the retainer and the outside of the retainer is resting against the body tube.

Use a sharpened pencil or other marking implement that will reach and mark the location of the bottom of the bottom slot, and the top of the top slot on the motor mount tube.

Remove the assembly and connect the marks to create two circles around the motor mount tube. If a centering ring will fit over the tube, you can use it as a guide for your circles. The space between the circles is where the fins will contact the motor mount tube and needs to be kept clear of epoxy or other materials while assembling the rocket before attaching the fins. The space between the ring for the top of the retainer and the bottom of the fins is where the bottom centering ring may be epoxied in place.

**Note** The strength of the bond between the fins and the motor mount can be greatly increased by putting internal fillets between the fins and motor mount tube, and the fins and the body tube. That strength is not needed for motors with 180 Ns of impulse and below, but should be considered if going above 180 Ns, and is required in the class 54mm fiberglass rocket. The next step makes creating internal fillets very difficult.

Spread some epoxy on the outside of the motor tube somewhere between the retainer-ring mark and the bottom-of-the-fins mark and slide the bottom ring (without the notch) up the tube until it is centered between the marks, and wait for the epoxy to set. Be sure to clean off any epoxy that strayed beyond the lines.

The placement of the top ring (the one with the notch) isn't critical: It should be above the top of the fin mark, but no closer than 1/4" from the end of the tube. Usually about 1/2" for the top of the tube is about right. Spread some epoxy on the outside of the motor tube at your chosen location and slide the top ring (with the notch) up the tube until it is in position, and wait for the epoxy to set. Be sure to clean off any epoxy that strayed into the fin or motor retainer zones.

Using JB-Weld (not any other epoxy) attach the inner part of the motor retainer to the bottom of the motor mount assembly. Spread the JB-Weld on the motor mount tube and not inside the motor retainer. Twist the motor retainer as you push it onto the tube.

Inspect the inside of the motor mount tube-motor retainer and thoroughly wipe away any JB-Weld that made it inside.

Place the assembly vertically (with the top notched ring pointed up), and let cure for at least 3 hours, preferably in a warm space. JB-Weld takes 24-48 hours to fully cure, but will usually not run after 3 hours.

## Step 3: Shock Cord

The shock cord in this kit consists of a shorter section of Kevlar and a longer section of nylon cording. The two sections should be tied together using the line form of a [double fisherman’s knot](https://en.wikipedia.org/wiki/Double_fisherman's_knot) ([REI Video](https://youtu.be/YHUv-oOMwRA)). The Kevlar section will be attached to the motor mount and the nylon section will be attached to the payload section.
Apply some epoxy like a fillet between the lower side of the top centering ring and the motor mount and wrap the Kevlar end of the shock cord around the motor mount into the epoxy. Make sure the cord lays flat enough so it will not interfere with the body tube when you slide the motor tube inside. Make sure the cord is secure and will not come loose later with ejection forces that will pull on the shock cord.

## Step 4: Forward Section

Insert the eyebolt through the hole in the center of the bulkhead and secure using the washer and nut.

**Apply some epoxy or CA to the nut and eyebolt threads to ensure the nut doesn’t come loose later.**

Cut off the eyebolt (Dremel or hacksaw) leaving about 1/4"-to-1/8" above the nut and file or sand the end to remove any sharp edges.

**Note** The coupler tube may be hidden inside either the payload tube or the body tube. Reach inside and slide it out.

Mark a line around the inside of the coupler tube 1/8" from the end. Apply epoxy to the inside of the tube and push the bulkhead in so that the line is visible and wait until the glue sets. There are two pieces that can assist you. The first is a spacer that can be placed against the bulkhead to hold it at the correct depth until the epoxy cures. The second is a stand with room for the eyebolt to hang down that will let you hold the spacer and bulkhead in the proper position while the epoxy cures.

Apply a fillet of epoxy around the inside edge of the coupler bulkhead joint.

Mark a line around the coupler 2" from the open end. Apply a very thin amount of epoxy on the first inch of the outside of the coupler, and twist and slide the coupler into the payload tube (forward body tube) until you reach the 2" mark. Quickly wipe off any excess epoxy at the payload tube-coupler joint. The payload tube will not join properly with the body tube if you leave excess epoxy at the joint.

Measure down 1 9/16" from the shoulder of the nose cone, and using an X-acto knife or a saw, cut off the bottom of the nose cone, and if necessary, sand the cut square. It will be pressing against the avionics carrier and should be as square as possible.

Insert the nose cone into the top of the payload tube.

Holes for Payload – Nose Cone Screws: Mark three points equally spaced around the circumference of the payload tube halfway between the shoulder and the end of the payload tube. Easiest is to wrap a piece of paper around the tube and mark one circumference. Unwrap and measure the circumference and divide the distance by three and mark the paper accordingly, then transfer the marks to the payload tube by wrapping the paper back around the tube and marking.

Holes for Altimeter Vents: Repeat the marking procedure 1" above the coupler-payload tube edge.

Drill all six holes with a #52, #51, or #50 bit. Drill slowly to try to leave the inside edges of the holes as clean as possible. You might consider drilling, tapping, and putting in a screw for the first hole before drilling the other five, to avoid the tube and nose cone rotating relative to each other.

Tap the top three holes with a #2-56 tap. These will secure the nose cone to the payload section.

Screw a pan-head #2-56 screw into each threaded hole. These will hold the nose cone on during flight, but permit it to be removed to access the avionics.

The other three holes are to permit the altimeter to measure the free stream pressure outside the rocket for calculating the altitude.

If you are going to install an avionics carrier, you will want to put a layer of foam in the bottom of the payload section.

## Step 5: Insert Motor Mount

Hold the motor mount assembly by the body tube at the position that it will be when epoxied in. Measure how far up the body tube the front centering ring will be.

Using sandpaper attached to the end of a dowel, roughen up the inside of the body tube where the front centering ring will be attached.

Put the shock cord inside of the motor mount tube so it's out of the way while the motor mount assembly is epoxied in.

Screw the outside of the motor retainer onto the end of the motor mount assembly.

**Important** The next several steps need to be completed quickly, before a batch of epoxy has time to set.

Using one or more craft (popsicle) sticks taped together, place a ring of epoxy inside the body tube about 1/4" short of where the front centering ring will sit. You need to get the epoxy up the tube without dripping anywhere else in the tube.

Insert the motor mount assembly part-way up the body tube.

Put a ring of epoxy around the lower end of the body tube between the bottom end and the fin slots.

Push and twist the motor mount assembly into the body tube. Be sure the bottom ring doesn't extend into the fin slots.

Make sure the rocket is vertical until the epoxy cures.

Launch Lug Marking: 
* It's easiest to mark the body tube for the launch lugs before putting on the fins. 
* Place a length of angle iron so that one edge is halfway between two sets of fin slots, and draw a vertical line up the body tube.

## Step 6: Fins

Dry fit the fins and if necessary sand the slots until the fins fit. You don't want them to be a loose fit.

Make sure you have two or three fin jigs handy.

**Important** The next several steps need to be completed quickly, before a batch of epoxy has time to set.

Apply a generous-but-not-overflowing amount of epoxy to the root end of each fin tang and insert it into the fin slots.

Before the epoxy sets, place a fin jig on each side of the fins and place the assembly on a table to guarantee the fins are straight. A third jig at the end of the body tube will help you keep things level

Before proceeding, make sure the epoxy has fully cured.

## Step 7: Fin Fillets

Get a set of plastic spoons that will be used for pulling the fillets.

Rub the edges of the spoon heavily with a pencil lead.

Draw the spoon along the joint between the fin and the body tube. With luck, you'll see a line where the spoon met the fin and where it met the body tube.

Place blue tape along each line.

Repeat the marking and taping for each of the remaining fin-body-tube joints.

Place blue tape at the top and bottom of the fin/body tube where you want the fillet to end.

Plan on doing two fillets at a time between adjacent fins.

Measure out a batch of glass microballoons equal in volume to the batch of epoxy you are about to mix.

Mix a batch of epoxy and quickly fold in the microballoons. It should have roughly the consistency of peanut butter.

Lay the epoxy down in the joint and roughly smooth it with the stir stick.

Using a plastic spoon, pull along the fillet, leaving a nice concave profile, with excess epoxy being gathered up by the spoon.

Quickly touch up any flaws.

Remove the blue tape along that particular set of fillets.

Let them fully cure before moving on to the next fillets.

**Sand both the body tube and the launch lug where they are going to join until you have removed the glassine (the white, shiny paper layer). Failure to do so may result in moments of panic at the launch stand when your launch lugs break off.**

The launch lugs should be epoxied on and aligned with the vertical line you drew earlier. Placement isn't critical, but the bottom one should be somewhere in between the top edge of the fins and the bottom edge of the fins (Madcow recommends 2" from the bottom of the rocket). The top one should be at least an inch or two below the top of the body tube. Madcow recommends at the center of pressure, which is 27" from the nose tip. Make sure they are aligned along the body tube.

## Step 8: Chute Protector and Parachute
Shake or push the shock cord free out the top of the body tube.

Thread the chute protector through the shock cord and slide down to the body.

Roughly 2/3 of the shock cord length (the length from the body tube up) tie a [butterfly knot](https://www.101knots.com/butterfly-knot.html) or a [figure eight knot on a bight](https://www.101knots.com/figure-8-on-a-bight.html).

Attach the end of the shock cord to the screw eye in the payload section with a [PML knot](https://www.bing.com/ck/a?!&&p=166c64ea976c196aJmltdHM9MTcyODI1OTIwMCZpZ3VpZD0zZGZjOTQ2Yy1iNTBmLTYwNGItMjIzOC04MDg0YjRmMTYxY2MmaW5zaWQ9NTIxOQ&ptn=3&ver=2&hsh=3&fclid=3dfc946c-b50f-604b-2238-8084b4f161cc&psq=PML+knot+rocketry&u=a1aHR0cHM6Ly93d3cubmFra2Etcm9ja2V0cnkubmV0L2FydGljbGVzL3BtbGNodXRlcGFja2luZy5wZGY&ntb=1) and secure the end to the body with either electrical or blue tape rather than epoxy.

Attach the parachute to the butterfly knot or the figure eight knot on a bight with a Lark's Head knot. Gather the shroud-line loops. Push them through the bight on the shock cord. Pass the parachute through the shroud-line loops and pull.

If you want to fold the parachute and pack it in the rocket use the [Instructions for Folding Parachutes](https://dofpro.org/RCK/const/index)

## Step 9: Painting

If you desire to paint your rocket, please do so. There are lots of places on-line that will give you an overabundance of advice on how to do so. Many fliers prefer to make their rocket “earn it's paint” by flying it unpainted, and then painting it if it survives the first flight.

* You should mark the center of pressure with a center-of-pressure symbol, which is a circle with a dot in the middle, ⊙. A Sharpie® works great, but we do have water-slide decals if you want to get fancy.

* Label the rocket with your name and cell-phone number on both the body tube and payload section. Again a Sharpie® works great, but you can use print-on adhesive labels or Sam's labeling machine as well.